import { Flight, Hotel, Bus, Activity, Location } from "@/types/travel";

export const locations: Location[] = [
  { id: "1", city: "New York", country: "USA", code: "JFK" },
  { id: "2", city: "London", country: "UK", code: "LHR" },
  { id: "3", city: "Paris", country: "France", code: "CDG" },
  { id: "4", city: "Tokyo", country: "Japan", code: "NRT" },
  { id: "5", city: "Dubai", country: "UAE", code: "DXB" },
  { id: "6", city: "Singapore", country: "Singapore", code: "SIN" },
  { id: "7", city: "Mumbai", country: "India", code: "BOM" },
  { id: "8", city: "Delhi", country: "India", code: "DEL" },
  { id: "9", city: "Bangalore", country: "India", code: "BLR" },
  { id: "10", city: "Los Angeles", country: "USA", code: "LAX" },
];

export const mockFlights: Flight[] = [
  {
    id: "FL001",
    airline: "Air India",
    flightNumber: "AI 101",
    from: locations[7],
    to: locations[0],
    departure: "2024-03-15T10:30:00",
    arrival: "2024-03-15T22:45:00",
    duration: "15h 15m",
    price: 45000,
    currency: "INR",
    class: "economy",
    stops: 1,
    seats: 24,
    baggage: "2 pieces, 23kg each",
    amenities: ["WiFi", "In-flight entertainment", "Meals included"],
  },
  {
    id: "FL002",
    airline: "Emirates",
    flightNumber: "EK 505",
    from: locations[7],
    to: locations[4],
    departure: "2024-03-16T03:00:00",
    arrival: "2024-03-16T05:30:00",
    duration: "3h 30m",
    price: 18500,
    currency: "INR",
    class: "business",
    stops: 0,
    seats: 12,
    baggage: "3 pieces, 32kg each",
    amenities: ["Lounge access", "Flatbed seats", "Gourmet meals", "WiFi"],
  },
  {
    id: "FL003",
    airline: "IndiGo",
    flightNumber: "6E 1234",
    from: locations[7],
    to: locations[8],
    departure: "2024-03-17T06:00:00",
    arrival: "2024-03-17T08:15:00",
    duration: "2h 15m",
    price: 4500,
    currency: "INR",
    class: "economy",
    stops: 0,
    seats: 45,
    baggage: "1 piece, 15kg",
    amenities: ["Snacks available", "USB charging"],
  },
];

export const mockHotels: Hotel[] = [
  {
    id: "HT001",
    name: "The Taj Mahal Palace",
    location: locations[7],
    rating: 4.8,
    reviews: 2450,
    pricePerNight: 15000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945",
    amenities: [
      "Pool",
      "Spa",
      "Restaurant",
      "Free WiFi",
      "Gym",
      "Room service",
    ],
    roomType: "Deluxe Room",
    availability: true,
    cancellationPolicy: "Free cancellation up to 24 hours before check-in",
    description:
      "Iconic luxury hotel with stunning views and world-class service.",
  },
  {
    id: "HT002",
    name: "ITC Grand Central",
    location: locations[7],
    rating: 4.6,
    reviews: 1820,
    pricePerNight: 12000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb",
    amenities: ["Restaurant", "Bar", "Free WiFi", "Business center", "Gym"],
    roomType: "Executive Room",
    availability: true,
    cancellationPolicy: "Free cancellation up to 48 hours before check-in",
    description:
      "Modern business hotel with excellent amenities and central location.",
  },
  {
    id: "HT003",
    name: "Oberoi Mumbai",
    location: locations[7],
    rating: 4.9,
    reviews: 3100,
    pricePerNight: 22000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4",
    amenities: [
      "Pool",
      "Spa",
      "Fine dining",
      "Butler service",
      "Free WiFi",
      "Gym",
    ],
    roomType: "Premier Room",
    availability: true,
    cancellationPolicy: "Free cancellation up to 72 hours before check-in",
    description:
      "Ultra-luxury hotel offering personalized service and breathtaking views.",
  },
];

export const mockBuses: Bus[] = [
  {
    id: "BS001",
    operator: "VRL Travels",
    from: locations[7],
    to: locations[8],
    departure: "2024-03-15T22:00:00",
    arrival: "2024-03-16T09:00:00",
    duration: "11h",
    price: 1200,
    currency: "INR",
    busType: "sleeper",
    seats: 18,
    amenities: ["AC", "Blanket", "Water bottle", "Charging point"],
  },
  {
    id: "BS002",
    operator: "Red Bus Express",
    from: locations[7],
    to: locations[9],
    departure: "2024-03-16T20:30:00",
    arrival: "2024-03-17T06:30:00",
    duration: "10h",
    price: 1500,
    currency: "INR",
    busType: "sleeper",
    seats: 12,
    amenities: ["AC", "WiFi", "Snacks", "Reading light", "Charging point"],
  },
  {
    id: "BS003",
    operator: "Orange Travels",
    from: locations[8],
    to: locations[9],
    departure: "2024-03-17T23:00:00",
    arrival: "2024-03-18T05:00:00",
    duration: "6h",
    price: 800,
    currency: "INR",
    busType: "semi-sleeper",
    seats: 22,
    amenities: ["AC", "Water bottle", "Blanket"],
  },
];

export const mockActivities: Activity[] = [
  {
    id: "AC001",
    name: "Gateway of India Walking Tour",
    location: locations[7],
    category: "Cultural",
    rating: 4.7,
    reviews: 890,
    price: 500,
    currency: "INR",
    duration: "3 hours",
    image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da",
    description:
      "Explore the historic Gateway of India and surrounding areas with an expert guide.",
    included: ["Professional guide", "Refreshments", "Entry fees"],
    availability: true,
  },
  {
    id: "AC002",
    name: "Elephanta Caves Tour",
    location: locations[7],
    category: "Historical",
    rating: 4.8,
    reviews: 1240,
    price: 1200,
    currency: "INR",
    duration: "5 hours",
    image: "https://images.unsplash.com/photo-1548013146-72479768bada",
    description:
      "Discover ancient rock-cut caves on Elephanta Island with ferry and guide.",
    included: ["Ferry tickets", "Guide", "Entry fees", "Lunch"],
    availability: true,
  },
  {
    id: "AC003",
    name: "Bollywood Studio Tour",
    location: locations[7],
    category: "Entertainment",
    rating: 4.6,
    reviews: 670,
    price: 2500,
    currency: "INR",
    duration: "4 hours",
    image: "https://images.unsplash.com/photo-1478720568477-152d9b164e26",
    description:
      "Go behind the scenes at a real Bollywood film studio and witness live shooting.",
    included: ["Transport", "Guide", "Studio access", "Snacks"],
    availability: true,
  },
];
