import { db } from "@/db";
import { activities } from "@/db/schema";

async function main() {
  const sampleActivities = [
    {
      title: "Skydiving Experience",
      location: "Strip Boulevard, Las Vegas, Nevada",
      city: "Las Vegas",
      description:
        "Experience the ultimate adrenaline rush with a tandem skydive over the Las Vegas Strip with certified instructors. See iconic landmarks from 15,000 feet above the desert.",
      category: "Adventure",
      duration: "4 hours",
      price: 25000,
      rating: 4.9,
      maxParticipants: 8,
      availableSpots: 5,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-1-1.jpg",
        "https://images.unsplash.com/activity-1-2.jpg",
        "https://images.unsplash.com/activity-1-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Scuba Diving Certification",
      location: "Great Barrier Reef, Cairns, Queensland",
      city: "Cairns",
      description:
        "Obtain your PADI Open Water certification while exploring the breathtaking Great Barrier Reef. Learn from experienced instructors in crystal-clear tropical waters.",
      category: "Adventure",
      duration: "8 hours",
      price: 28000,
      rating: 4.8,
      maxParticipants: 10,
      availableSpots: 6,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-2-1.jpg",
        "https://images.unsplash.com/activity-2-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Bungee Jumping",
      location: "Kawarau Bridge, Queenstown, New Zealand",
      city: "Queenstown",
      description:
        "Take the leap from the world-famous Kawarau Bridge, birthplace of commercial bungee jumping. Feel the rush of freefalling 43 meters toward pristine turquoise waters.",
      category: "Adventure",
      duration: "3 hours",
      price: 18000,
      rating: 4.9,
      maxParticipants: 6,
      availableSpots: 4,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-3-1.jpg",
        "https://images.unsplash.com/activity-3-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Helicopter Tour",
      location: "Grand Canyon National Park, Arizona",
      city: "Grand Canyon",
      description:
        "Soar over the magnificent Grand Canyon on an unforgettable helicopter tour. Witness stunning geological formations and the Colorado River from a bird's eye view.",
      category: "Adventure",
      duration: "5 hours",
      price: 30000,
      rating: 5.0,
      maxParticipants: 8,
      availableSpots: 3,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-4-1.jpg",
        "https://images.unsplash.com/activity-4-2.jpg",
        "https://images.unsplash.com/activity-4-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Parasailing Adventure",
      location: "Jomtien Beach, Pattaya, Thailand",
      city: "Pattaya",
      description:
        "Glide high above the stunning coastline of Pattaya while parasailing over the Gulf of Thailand. Enjoy panoramic ocean views and gentle sea breezes.",
      category: "Adventure",
      duration: "2 hours",
      price: 6500,
      rating: 4.6,
      maxParticipants: 10,
      availableSpots: 8,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-5-1.jpg",
        "https://images.unsplash.com/activity-5-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Zip Line Canopy Tour",
      location: "Monteverde Cloud Forest Reserve, Costa Rica",
      city: "Monteverde",
      description:
        "Zip through the lush cloud forest canopy on thrilling cables connecting tree platforms. Experience the rich biodiversity of Costa Rica from above.",
      category: "Adventure",
      duration: "4 hours",
      price: 14000,
      rating: 4.8,
      maxParticipants: 12,
      availableSpots: 9,
      includes: JSON.stringify([
        "Safety Equipment",
        "Professional Guide",
        "Insurance",
        "Photos",
        "Video",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-6-1.jpg",
        "https://images.unsplash.com/activity-6-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Louvre Museum Skip-the-Line Tour",
      location: "Rue de Rivoli, Paris, France",
      city: "Paris",
      description:
        "Bypass the crowds with priority access to the world's largest art museum. Explore masterpieces including the Mona Lisa and Venus de Milo with an expert guide.",
      category: "Culture",
      duration: "3 hours",
      price: 9500,
      rating: 4.7,
      maxParticipants: 20,
      availableSpots: 12,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-7-1.jpg",
        "https://images.unsplash.com/activity-7-2.jpg",
        "https://images.unsplash.com/activity-7-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Vatican Museums and Sistine Chapel",
      location: "Viale Vaticano, Rome, Italy",
      city: "Rome",
      description:
        "Discover the treasures of the Vatican with skip-the-line access to the museums and Michelangelo's breathtaking Sistine Chapel ceiling.",
      category: "Culture",
      duration: "4 hours",
      price: 11000,
      rating: 4.9,
      maxParticipants: 18,
      availableSpots: 10,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-8-1.jpg",
        "https://images.unsplash.com/activity-8-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Tea Ceremony Experience",
      location: "Gion District, Kyoto, Japan",
      city: "Kyoto",
      description:
        "Participate in an authentic Japanese tea ceremony led by a tea master in a traditional tatami room. Learn the ancient art and philosophy of this beautiful ritual.",
      category: "Culture",
      duration: "2 hours",
      price: 7500,
      rating: 4.8,
      maxParticipants: 8,
      availableSpots: 5,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-9-1.jpg",
        "https://images.unsplash.com/activity-9-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Flamenco Show with Dinner",
      location: "Barrio Santa Cruz, Seville, Spain",
      city: "Seville",
      description:
        "Experience passionate flamenco dancing and guitar in an intimate tablao setting. Enjoy authentic Andalusian cuisine and wine while watching world-class performers.",
      category: "Culture",
      duration: "3 hours",
      price: 12000,
      rating: 4.9,
      maxParticipants: 15,
      availableSpots: 7,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-10-1.jpg",
        "https://images.unsplash.com/activity-10-2.jpg",
        "https://images.unsplash.com/activity-10-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Broadway Show Tickets",
      location: "Theater District, New York City, New York",
      city: "New York City",
      description:
        "Secure premium seats to a hit Broadway musical in the heart of Manhattan's Theater District. Experience world-class performances and production quality.",
      category: "Culture",
      duration: "3 hours",
      price: 16000,
      rating: 4.8,
      maxParticipants: 20,
      availableSpots: 15,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-11-1.jpg",
        "https://images.unsplash.com/activity-11-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Traditional Thai Cooking Class",
      location: "Silom District, Bangkok, Thailand",
      city: "Bangkok",
      description:
        "Learn to prepare authentic Thai dishes from a professional chef in a modern cooking studio. Visit a local market and master techniques for pad thai, green curry, and more.",
      category: "Culture",
      duration: "5 hours",
      price: 8500,
      rating: 4.7,
      maxParticipants: 12,
      availableSpots: 8,
      includes: JSON.stringify([
        "Skip-the-Line Access",
        "Expert Guide",
        "Headsets",
        "Entry Tickets",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-12-1.jpg",
        "https://images.unsplash.com/activity-12-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Street Food Walking Tour",
      location: "Colaba Causeway, Mumbai, India",
      city: "Mumbai",
      description:
        "Explore Mumbai's vibrant street food scene with a local guide. Sample iconic dishes like vada pav, pani puri, and pav bhaji while learning about culinary traditions.",
      category: "Food",
      duration: "3 hours",
      price: 4500,
      rating: 4.6,
      maxParticipants: 15,
      availableSpots: 11,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-13-1.jpg",
        "https://images.unsplash.com/activity-13-2.jpg",
        "https://images.unsplash.com/activity-13-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Wine Tasting in Napa Valley",
      location: "Silverado Trail, Napa, California",
      city: "Napa",
      description:
        "Tour three premier Napa Valley wineries and sample award-winning wines. Learn about viticulture and winemaking while enjoying scenic vineyard views.",
      category: "Food",
      duration: "6 hours",
      price: 18000,
      rating: 4.9,
      maxParticipants: 12,
      availableSpots: 6,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-14-1.jpg",
        "https://images.unsplash.com/activity-14-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Gourmet Food Tour",
      location: "Gothic Quarter, Barcelona, Spain",
      city: "Barcelona",
      description:
        "Discover Barcelona's culinary treasures on a guided food tour through historic neighborhoods. Taste tapas, jamón ibérico, and local wines at authentic establishments.",
      category: "Food",
      duration: "4 hours",
      price: 13000,
      rating: 4.8,
      maxParticipants: 14,
      availableSpots: 9,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-15-1.jpg",
        "https://images.unsplash.com/activity-15-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Sushi Making Class",
      location: "Tsukiji Outer Market, Tokyo, Japan",
      city: "Tokyo",
      description:
        "Master the art of sushi preparation with a professional itamae chef. Learn knife skills, rice preparation, and create your own nigiri and maki rolls.",
      category: "Food",
      duration: "3 hours",
      price: 11500,
      rating: 4.9,
      maxParticipants: 10,
      availableSpots: 7,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-16-1.jpg",
        "https://images.unsplash.com/activity-16-2.jpg",
        "https://images.unsplash.com/activity-16-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Pasta Making Workshop",
      location: "San Lorenzo Market, Florence, Italy",
      city: "Florence",
      description:
        "Create traditional Tuscan pasta from scratch in a rustic Florentine kitchen. Learn to make tagliatelle, ravioli, and authentic Italian sauces with fresh ingredients.",
      category: "Food",
      duration: "4 hours",
      price: 10500,
      rating: 4.7,
      maxParticipants: 12,
      availableSpots: 8,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-17-1.jpg",
        "https://images.unsplash.com/activity-17-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Night Market Food Tour",
      location: "Raohe Street, Taipei, Taiwan",
      city: "Taipei",
      description:
        "Navigate Taipei's bustling night markets with a local foodie guide. Sample beloved street food classics like stinky tofu, beef noodle soup, and bubble tea.",
      category: "Food",
      duration: "3 hours",
      price: 5500,
      rating: 4.6,
      maxParticipants: 16,
      availableSpots: 12,
      includes: JSON.stringify([
        "Food Tastings",
        "Recipe Book",
        "Ingredients",
        "Beverages",
        "Chef Instruction",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-18-1.jpg",
        "https://images.unsplash.com/activity-18-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Eiffel Tower Summit Access",
      location: "Champ de Mars, Paris, France",
      city: "Paris",
      description:
        "Skip the lines and ascend to the summit of Paris's iconic Eiffel Tower. Enjoy breathtaking 360-degree views of the City of Light from the highest observation deck.",
      category: "Sightseeing",
      duration: "2 hours",
      price: 8000,
      rating: 4.8,
      maxParticipants: 20,
      availableSpots: 14,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-19-1.jpg",
        "https://images.unsplash.com/activity-19-2.jpg",
        "https://images.unsplash.com/activity-19-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Statue of Liberty & Ellis Island",
      location: "Liberty Island, New York City, New York",
      city: "New York City",
      description:
        "Take a ferry to Liberty Island and explore the Statue of Liberty and Ellis Island Immigration Museum. Learn about American immigration history with reserved access.",
      category: "Sightseeing",
      duration: "5 hours",
      price: 12500,
      rating: 4.7,
      maxParticipants: 18,
      availableSpots: 10,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-20-1.jpg",
        "https://images.unsplash.com/activity-20-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Dubai City Tour with Burj Khalifa",
      location: "Downtown Dubai, Dubai, UAE",
      city: "Dubai",
      description:
        "Discover Dubai's highlights including the Palm Jumeirah, Dubai Marina, and skip-the-line access to the Burj Khalifa observation deck on the 124th floor.",
      category: "Sightseeing",
      duration: "6 hours",
      price: 15000,
      rating: 4.8,
      maxParticipants: 16,
      availableSpots: 11,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-21-1.jpg",
        "https://images.unsplash.com/activity-21-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Sydney Opera House Tour",
      location: "Bennelong Point, Sydney, Australia",
      city: "Sydney",
      description:
        "Go behind the scenes of the world-famous Sydney Opera House with an expert guide. Explore theaters, rehearsal rooms, and learn about this architectural masterpiece.",
      category: "Sightseeing",
      duration: "2 hours",
      price: 7000,
      rating: 4.6,
      maxParticipants: 20,
      availableSpots: 15,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-22-1.jpg",
        "https://images.unsplash.com/activity-22-2.jpg",
        "https://images.unsplash.com/activity-22-3.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "London Eye Fast Track Tickets",
      location: "South Bank, London, UK",
      city: "London",
      description:
        "Experience stunning panoramic views of London from the iconic London Eye observation wheel. Fast-track entry ensures minimal wait time for your 30-minute rotation.",
      category: "Sightseeing",
      duration: "2 hours",
      price: 9000,
      rating: 4.5,
      maxParticipants: 20,
      availableSpots: 13,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-23-1.jpg",
        "https://images.unsplash.com/activity-23-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
    {
      title: "Golden Gate Bridge Bike Tour",
      location: "Fisherman's Wharf, San Francisco, California",
      city: "San Francisco",
      description:
        "Cycle across the iconic Golden Gate Bridge to charming Sausalito with stunning bay views. Enjoy a leisurely ride through scenic waterfront paths and historic neighborhoods.",
      category: "Sightseeing",
      duration: "4 hours",
      price: 8500,
      rating: 4.7,
      maxParticipants: 15,
      availableSpots: 9,
      includes: JSON.stringify([
        "Transportation",
        "Guide",
        "Entry Fees",
        "Audio Guide",
        "Map",
      ]),
      images: JSON.stringify([
        "https://images.unsplash.com/activity-24-1.jpg",
        "https://images.unsplash.com/activity-24-2.jpg",
      ]),
      createdAt: new Date().toISOString(),
    },
  ];

  await db.insert(activities).values(sampleActivities);

  console.log("✅ Activities seeder completed successfully");
}

main().catch((error) => {
  console.error("❌ Seeder failed:", error);
});
