import { db } from "@/db";
import { hotels } from "@/db/schema";

async function main() {
  const sampleHotels = [
    {
      name: "The Plaza Hotel",
      location: "Fifth Avenue, New York",
      city: "New York",
      rating: 4.8,
      pricePerNight: 45000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Presidential Suite",
      availableRooms: 12,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-1-1.jpg",
        "https://images.unsplash.com/hotel-1-2.jpg",
        "https://images.unsplash.com/hotel-1-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "The Ritz London",
      location: "Piccadilly, London",
      city: "London",
      rating: 5.0,
      pricePerNight: 50000,
      amenities: [
        "Free WiFi",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Luxury Suite",
      availableRooms: 8,
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-2-1.jpg",
        "https://images.unsplash.com/hotel-2-2.jpg",
        "https://images.unsplash.com/hotel-2-3.jpg",
        "https://images.unsplash.com/hotel-2-4.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Hotel Le Bristol",
      location: "Rue du Faubourg, Paris",
      city: "Paris",
      rating: 4.9,
      pricePerNight: 48000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Valet Parking",
        "24/7 Front Desk",
      ],
      roomType: "Executive Suite",
      availableRooms: 10,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-3-1.jpg",
        "https://images.unsplash.com/hotel-3-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Park Hyatt Tokyo",
      location: "Shinjuku, Tokyo",
      city: "Tokyo",
      rating: 4.8,
      pricePerNight: 42000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Deluxe Room",
      availableRooms: 15,
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-4-1.jpg",
        "https://images.unsplash.com/hotel-4-2.jpg",
        "https://images.unsplash.com/hotel-4-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Burj Al Arab",
      location: "Jumeirah Beach, Dubai",
      city: "Dubai",
      rating: 5.0,
      pricePerNight: 50000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Airport Shuttle",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Presidential Suite",
      availableRooms: 5,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-5-1.jpg",
        "https://images.unsplash.com/hotel-5-2.jpg",
        "https://images.unsplash.com/hotel-5-3.jpg",
        "https://images.unsplash.com/hotel-5-4.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Marina Bay Sands",
      location: "Marina Bay, Singapore",
      city: "Singapore",
      rating: 4.7,
      pricePerNight: 38000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Luxury Suite",
      availableRooms: 20,
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-6-1.jpg",
        "https://images.unsplash.com/hotel-6-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "The Langham Sydney",
      location: "The Rocks, Sydney",
      city: "Sydney",
      rating: 4.5,
      pricePerNight: 32000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "24/7 Front Desk",
      ],
      roomType: "Executive Suite",
      availableRooms: 18,
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-7-1.jpg",
        "https://images.unsplash.com/hotel-7-2.jpg",
        "https://images.unsplash.com/hotel-7-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Raffles Hotel",
      location: "Beach Road, Singapore",
      city: "Singapore",
      rating: 4.9,
      pricePerNight: 46000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Luxury Suite",
      availableRooms: 9,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-8-1.jpg",
        "https://images.unsplash.com/hotel-8-2.jpg",
        "https://images.unsplash.com/hotel-8-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Grand Hyatt Hong Kong",
      location: "Wan Chai, Hong Kong",
      city: "Hong Kong",
      rating: 4.7,
      pricePerNight: 35000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Airport Shuttle",
        "24/7 Front Desk",
      ],
      roomType: "Deluxe Room",
      availableRooms: 25,
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-9-1.jpg",
        "https://images.unsplash.com/hotel-9-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "The Peninsula Bangkok",
      location: "Riverside, Bangkok",
      city: "Bangkok",
      rating: 4.8,
      pricePerNight: 28000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Airport Shuttle",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Executive Suite",
      availableRooms: 22,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-10-1.jpg",
        "https://images.unsplash.com/hotel-10-2.jpg",
        "https://images.unsplash.com/hotel-10-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Fairmont Banff Springs",
      location: "Banff, Alberta, Canada",
      city: "Banff",
      rating: 4.5,
      pricePerNight: 24000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Deluxe Room",
      availableRooms: 30,
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-11-1.jpg",
        "https://images.unsplash.com/hotel-11-2.jpg",
        "https://images.unsplash.com/hotel-11-3.jpg",
        "https://images.unsplash.com/hotel-11-4.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Hotel Arts Barcelona",
      location: "Olympic Port, Barcelona",
      city: "Barcelona",
      rating: 4.7,
      pricePerNight: 34000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "24/7 Front Desk",
      ],
      roomType: "Executive Suite",
      availableRooms: 16,
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-12-1.jpg",
        "https://images.unsplash.com/hotel-12-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "The Oberoi Mumbai",
      location: "Nariman Point, Mumbai",
      city: "Mumbai",
      rating: 4.8,
      pricePerNight: 26000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Airport Shuttle",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Luxury Suite",
      availableRooms: 14,
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-13-1.jpg",
        "https://images.unsplash.com/hotel-13-2.jpg",
        "https://images.unsplash.com/hotel-13-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Four Seasons Seoul",
      location: "Gwanghwamun, Seoul",
      city: "Seoul",
      rating: 4.9,
      pricePerNight: 40000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Presidential Suite",
      availableRooms: 11,
      checkIn: "2:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-14-1.jpg",
        "https://images.unsplash.com/hotel-14-2.jpg",
        "https://images.unsplash.com/hotel-14-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Atlantis The Palm",
      location: "Palm Jumeirah, Dubai",
      city: "Dubai",
      rating: 4.5,
      pricePerNight: 36000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Airport Shuttle",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Deluxe Room",
      availableRooms: 40,
      checkIn: "3:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-15-1.jpg",
        "https://images.unsplash.com/hotel-15-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Mandarin Oriental Paris",
      location: "Rue Saint-Honoré, Paris",
      city: "Paris",
      rating: 5.0,
      pricePerNight: 50000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Presidential Suite",
      availableRooms: 7,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-16-1.jpg",
        "https://images.unsplash.com/hotel-16-2.jpg",
        "https://images.unsplash.com/hotel-16-3.jpg",
        "https://images.unsplash.com/hotel-16-4.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Rosewood London",
      location: "High Holborn, London",
      city: "London",
      rating: 4.8,
      pricePerNight: 44000,
      amenities: [
        "Free WiFi",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Luxury Suite",
      availableRooms: 13,
      checkIn: "2:00 PM",
      checkOut: "11:00 AM",
      images: [
        "https://images.unsplash.com/hotel-17-1.jpg",
        "https://images.unsplash.com/hotel-17-2.jpg",
        "https://images.unsplash.com/hotel-17-3.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
    {
      name: "Aman Tokyo",
      location: "Otemachi, Tokyo",
      city: "Tokyo",
      rating: 4.9,
      pricePerNight: 47000,
      amenities: [
        "Free WiFi",
        "Swimming Pool",
        "Fitness Center",
        "Spa",
        "Restaurant",
        "Room Service",
        "Concierge",
        "Business Center",
        "Valet Parking",
        "Bar & Lounge",
        "24/7 Front Desk",
      ],
      roomType: "Executive Suite",
      availableRooms: 10,
      checkIn: "3:00 PM",
      checkOut: "12:00 PM",
      images: [
        "https://images.unsplash.com/hotel-18-1.jpg",
        "https://images.unsplash.com/hotel-18-2.jpg",
      ],
      createdAt: new Date().toISOString(),
    },
  ];

  await db.insert(hotels).values(sampleHotels);

  console.log("✅ Hotels seeder completed successfully");
}

main().catch((error) => {
  console.error("❌ Seeder failed:", error);
});
